import { useCallback, useEffect, useState } from 'react';
import { api } from '../api';
import { CityVisualization, WaterChart, type ChartPoint } from '../components/visuals';
import { Card, Empty, Loading, Notice, StateBadge, Stat } from '../components/ui';

/**
 * Explicitly labelled simulation mode.
 *
 * Simulation samples are written to the same telemetry, event, command and
 * notification tables as real device data, but every row is flagged as simulated
 * and the node is named as a simulation node. The banner below is permanent.
 */

export default function SimulationPage() {
  const [state, setState] = useState<Record<string, unknown> | null>(null);
  const [history, setHistory] = useState<Array<Record<string, unknown>>>([]);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [intervalSeconds, setIntervalSeconds] = useState(5);
  const [pattern, setPattern] = useState('sine');
  const [level, setLevel] = useState(20);

  const load = useCallback(async () => {
    try {
      const result = await api.simulationState();
      setState(result as unknown as Record<string, unknown>);
      setHistory((result.history || []) as unknown as Array<Record<string, unknown>>);
      setError(null);
    } catch (err) { setError((err as Error).message); }
  }, []);

  useEffect(() => {
    void load();
    const timer = setInterval(() => void load(), 10_000);
    return () => clearInterval(timer);
  }, [load]);

  async function step(scenario?: string) {
    setBusy(true); setMessage(null); setError(null);
    try {
      const result = await api.simulationStep(scenario ? { scenario } : { levelCm: level });
      setMessage(result.message);
      await load();
    } catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }

  async function start() {
    setBusy(true); setError(null);
    try { await api.simulationStart(intervalSeconds, pattern); setMessage('Simulation started. Every sample is labelled SIMULATION.'); await load(); }
    catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }

  async function stop() {
    setBusy(true); setError(null);
    try { await api.simulationStop(); setMessage('Simulation stopped.'); await load(); }
    catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }

  if (!state) return <Loading label="Loading simulation state…" />;

  const device = state.device as Record<string, unknown> | null;
  const running = Boolean(state.running);

  return (
    <div className="stack" style={{ gap: '1.25rem' }}>
      <div className="page-head">
        <div>
          <h1>Simulation mode</h1>
          <p>Drive the full flood workflow without physical hardware. Everything produced here is labelled as simulated.</p>
        </div>
        <span className="badge unknown">SIMULATION ONLY</span>
      </div>

      <Notice tone="simulation">
        SIMULATION: samples below are generated by the platform, not by a physical sensor. They are flagged in telemetry, flood events,
        barrier commands, notifications and the public status page.
      </Notice>

      {error && <Notice tone="critical">{error}</Notice>}
      {message && <Notice tone="success">{message}</Notice>}

      <div className="grid cols-4">
        <Stat label="Level" value={state.levelCm === null || state.levelCm === undefined ? '—' : `${Number(state.levelCm).toFixed(1)} cm`} detail="Latest simulated sample" />
        <Stat label="State" value={device ? String(device.currentState) : '—'} detail={running ? 'Auto-running' : 'Manual steps'} tone={(device ? String(device.currentState) : undefined) as 'normal' | 'watch' | 'warning' | 'critical' | 'recovery' | 'unknown' | undefined} />
        <Stat label="Barrier" value={device ? String(device.barrierState) : '—'} detail={device?.emergencyStopActive ? 'E-stop latched' : 'Normal'} />
        <Stat label="Events" value={String(state.eventCount ?? 0)} detail="Recorded from simulation" />
      </div>

      <div className="grid cols-2">
        <CityVisualization
          levelCm={state.levelCm === null || state.levelCm === undefined ? null : Number(state.levelCm)}
          state={device ? String(device.currentState) : 'NORMAL'}
          barrier={device ? String(device.barrierState) : 'DOWN'}
          simulated
          devices={[]}
        />
        <Card title="Manual steps" subtitle="Each step writes one labelled telemetry sample and runs the full engine">
          <div className="stack" style={{ gap: '0.5rem' }}>
            <div className="row">
              <button type="button" className="btn small" disabled={busy} onClick={() => void step('rise')}>Water rises +6 cm</button>
              <button type="button" className="btn secondary small" disabled={busy} onClick={() => void step('recede')}>Water recedes -7 cm</button>
            </div>
            <div className="row">
              <button type="button" className="btn secondary small" disabled={busy} onClick={() => void step('sensor-fault')}>Sensor fault</button>
              <button type="button" className="btn secondary small" disabled={busy} onClick={() => void step('sensor-recovered')}>Sensor recovered</button>
            </div>
            <div className="row">
              <button type="button" className="btn danger small" disabled={busy} onClick={() => void step('estop')}>Emergency stop</button>
              <button type="button" className="btn secondary small" disabled={busy} onClick={() => void step('estop-reset')}>Reset E-stop</button>
            </div>
            <div className="row">
              <input type="number" min={0} max={400} value={level} onChange={(event) => setLevel(Number(event.target.value))} style={{ width: 90, padding: '0.4rem', border: '1px solid var(--border-strong)', borderRadius: 6 }} aria-label="Level in centimetres" />
              <button type="button" className="btn secondary small" disabled={busy} onClick={() => void step()}>Set level</button>
            </div>
          </div>
        </Card>
      </div>

      <Card title="Automatic simulation" subtitle="Generates a labelled sample every interval using the selected pattern">
        <div className="row">
          <label className="field" style={{ marginBottom: 0, maxWidth: 160 }}>
            <span>Interval (seconds)</span>
            <input type="number" min={2} max={120} value={intervalSeconds} onChange={(event) => setIntervalSeconds(Number(event.target.value))} />
          </label>
          <label className="field" style={{ marginBottom: 0, maxWidth: 200 }}>
            <span>Pattern</span>
            <select value={pattern} onChange={(event) => setPattern(event.target.value)}>
              <option value="sine">Sine wave</option>
              <option value="rise">Steady rise</option>
              <option value="random">Random walk</option>
            </select>
          </label>
          {running
            ? <button type="button" className="btn danger" onClick={() => void stop()} disabled={busy}>Stop simulation</button>
            : <button type="button" className="btn" onClick={() => void start()} disabled={busy}>Start simulation</button>}
        </div>
      </Card>

      <Card title="Simulated water level">
        {history.length ? (
          <WaterChart history={history as unknown as ChartPoint[] as never} thresholds={{ watchCm: 25, warningCm: 40, criticalCm: 55 }} />
        ) : (
          <Empty>No simulated samples yet. Use a manual step or start the automatic simulation.</Empty>
        )}
      </Card>

      {state.lastEvent ? (
        <Card title="Last simulated event">
          <div className="row">
            <StateBadge state={String((state.lastEvent as Record<string, unknown>).toState)} />
            <span className="muted">
              {String((state.lastEvent as Record<string, unknown>).fromState)} → {String((state.lastEvent as Record<string, unknown>).toState)} · {String((state.lastEvent as Record<string, unknown>).reason || '')}
            </span>
          </div>
        </Card>
      ) : null}
    </div>
  );
}
